[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 7860
maxUploadSize = 200
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00FF00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 