# Configuration spécifique pour Hugging Face Spaces
# Ce fichier contient des paramètres sensibles et des configurations spéciales

[server]
# Désactiver les vérifications de sécurité pour éviter les erreurs 403
enableCORS = false
enableXsrfProtection = false

# Configuration pour les uploads de fichiers
maxUploadSize = 200

# Configuration pour Hugging Face Spaces
port = 7860
address = "0.0.0.0"

# Désactiver le file watcher pour éviter les problèmes de permissions
fileWatcherType = "none" 